# Generated by Django 4.2.1 on 2023-08-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=200)),
                ('developer_publisher', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('platforms', models.CharField(max_length=200)),
                ('cover_art', models.ImageField(upload_to='covers/')),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
