# Generated by Django 4.2.1 on 2023-08-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamedb',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='gamedb',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='gamedb',
            name='tags',
        ),
        migrations.AddField(
            model_name='gamedb',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='admindashboard.genre'),
        ),
        migrations.AddField(
            model_name='gamedb',
            name='platforms',
            field=models.ManyToManyField(related_name='games', to='admindashboard.platform'),
        ),
        migrations.AddField(
            model_name='gamedb',
            name='tags',
            field=models.ManyToManyField(related_name='games', to='admindashboard.tag'),
        ),
    ]
