# Generated by Django 4.2.4 on 2023-08-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0004_alter_gamedb_cover_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedb',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
