# Generated by Django 4.2.4 on 2023-08-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0005_alter_gamedb_cover_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedb',
            name='cover_art',
            field=models.ImageField(default='none', upload_to='covers/'),
            preserve_default=False,
        ),
    ]
