# Generated by Django 4.2.1 on 2023-09-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0007_alter_gamedb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedb',
            name='shortdesc',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamedb',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
