# Generated by Django 4.2.1 on 2023-09-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0008_gamedb_shortdesc_alter_gamedb_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedb',
            name='genres',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Role-Playing Game (RPG)', 'Role-Playing Game (RPG)'), ('Simulation', 'Simulation'), ('Strategy', 'Strategy'), ('Sports and Racing', 'Sports and Racing'), ('Puzzle', 'Puzzle'), ('Platformer', 'Platformer'), ('Horror', 'Horror'), ('Fighting', 'Fighting'), ('Music and Rhythm', 'Music and Rhythm'), ('Party and Mini-Games', 'Party and Mini-Games'), ('Educational', 'Educational'), ('Open World', 'Open World'), ('MMORPG (Massively Multiplayer Online Role-Playing Game)', 'MMORPG (Massively Multiplayer Online Role-Playing Game)')], default='Action', max_length=100),
        ),
    ]
