# Generated by Django 4.2.1 on 2023-09-10 14:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('admindashboard', '0009_alter_gamedb_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedb',
            name='tags',
        ),
        migrations.AddField(
            model_name='gamedb',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
