# Generated by Django 4.2.1 on 2023-10-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0011_userregisterdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userregisterdb',
        ),
    ]
