# Generated by Django 4.2.1 on 2023-10-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0017_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='comment',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
