# Generated by Django 4.2.4 on 2023-10-07 15:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userfrontend', '0004_alter_userregisterdb_password'),
        ('admindashboard', '0018_blogcomment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gamedb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.gamedb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userfrontend.userregisterdb')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
