# Generated by Django 4.2.1 on 2023-10-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userfrontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userregisterdb',
        ),
    ]
