# Generated by Django 4.2.1 on 2023-10-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userfrontend', '0002_delete_userregisterdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='userregisterdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=30)),
                ('password', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
